## numpy的常见用法整理

In [45]:
import numpy as np
print(np.__version__)

1.14.2


##### 创建数组

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 创建布尔数组
要求：数组大小为3*×3，全部为true

In [47]:
arr = np.full((3, 3), True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### 按要求修改数组中的元素
要求：原数组为一维数组，内容从0到9，将所有奇数原地修改为-1

In [48]:
arr = np.arange(0, 10)
arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### 按要求修改数组中的元素（返回新数组）
要求：原数组为一维数组，内容从0到9，返回一个数组的拷贝，其中奇数修改为-1

In [49]:
arr = np.arange(0 ,10)
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### 修改数组的形状
要求：将给定的一维数组reshape为二维数组，其中新数组的行数为2

In [50]:
arr = np.arange(0, 10)
arr.reshape(2, -1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 合并数组（列方向）
要求：将给定的数组在列方向上合并

In [51]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# 答案一
c = np.concatenate([a, b], axis=0)
print(c.shape)
# 答案二
d = np.vstack([a, b])
print(d.shape)
# 答案三
np.r_[a, b]

(4, 5)
(4, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### 合并数组（行方向）
要求：将给定的数组在水平方向上合并

In [52]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# 答案一
c = np.concatenate([a, b], axis=1)
print(c.shape)
# 答案二
d = np.hstack([a, b])
print(d.shape)
# 答案三
np.c_[a, b]

(2, 10)
(2, 10)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

##### 创建数组（进阶）
要求：不用硬编码，使用内置方法，从给定数组a生成数组b

In [53]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
c = np.r_[np.repeat(a, 3), np.tile(a, 3)]
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

##### 返回公共元素
要求：给定两个数组，要求返回这两个数组元素的交集

In [54]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

##### 删除元素
要求：给定两个数组a、b，从数组a中删除b中出现的元素

In [55]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)
np.setdiff1d(b, a)

array([6, 7, 8, 9])

##### 找出相同的元素
要求：给定两个数组a,b,返回两数组中相同数组中的下标

In [58]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
index = np.where(a == b)
a[index]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


array([], dtype=int64)

##### 按要求取出元素
要求：从数组中取出大于等于5且小于10的元素

In [60]:
a = np.arange(15)
# 答案一
index = np.where((a >= 5) & (a <= 10))
a[index]
# 答案二
index = np.where(np.logical_and(a >= 5, a <= 10))
print(a[index])
# 答案三
a[(a >= 5) & (a <= 10)]

[ 5  6  7  8  9 10]


array([ 5,  6,  7,  8,  9, 10])

##### 实现max的numpy版
要求：给定长度相同的数组a，b，返回一个新数组，数组上的每一个元素为max(a_i, b_i).
若pair_max为满足要求的函数，则对于a和h，期望输出如下：

In [61]:
a = np.array([5, 7, 9, 8, 6, 5, 4])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 4.])

##### 交换数组的列
要求：交换数组的第一和第二列

In [67]:
a = np.arange(9).reshape(3, 3)
print(a[:, [1, 0, 2]])

[[1 0 2]
 [4 3 5]
 [7 6 8]]


##### 交换数组的行
要求：交换两个数组的第一和第二行

In [68]:
a = np.arange(9).reshape(3, 3)
a[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

##### 将一个数组按行反序
要求：数组为二维数组，将其行反序

In [69]:
a = np.arange(9).reshape(3, 3)
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

##### 将一个数组按列反序
要求：数组为二维数组，将其列反序

In [71]:
a = np.arange(9).reshape(3, 3)
a[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

##### 创建随机数组
要求：创建一个5*3的数组，数组元素为5到10的随机浮点数

In [79]:
# 创建一个0到1的随机数
a = np.random.random((5, 3))
# 创建一个最小值为5，最大值为10的随机整数
rand_arr = np.random.randint(low=5, high=10, size=(5, 3))


# 答案二
rand_arr = np.random.uniform(5, 10, size=(5, 3))
rand_arr

array([[5.61432098, 8.63619258, 5.39751118],
       [9.96165392, 8.3320801 , 6.37766003],
       [6.35655749, 5.02226747, 7.22995755],
       [5.87013906, 9.00178657, 6.41499132],
       [8.06829695, 7.31276071, 9.64117644]])

##### 按要求打印数组
要求：数组元素输出时保留3位小数

In [81]:
rand_arr = np.random.uniform(5, 10, size=(5, 3))
np.set_printoptions(precision=3)
rand_arr[: 4]

array([[8.852, 9.306, 6.552],
       [9.611, 8.07 , 7.051],
       [9.835, 7.762, 8.517],
       [9.264, 6.76 , 6.724]])

###### 按要求打印数组（二）
要求：数组为小数，使用小数点的形式来打印，而不是科学计数法

In [84]:
np.random.seed(100)
rand_arr = np.random.random([3, 3]) / 1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

##### 按要求打印数组（三）
要求：打印时省略中间元素，限制显示数组元素的个数为6

In [87]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

##### 加载特殊矩阵
要求：著名的iris数据集是包含兰花属性和种类的数据集，其中每行属性有数字和文字，用numpy来加载他们

In [90]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petawidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

##### 重定义数组的元素范围
要求：将iris数组集的第一个列的数据范围缩放为0到1

In [96]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin) / (Smax - Smin)
np.set_printoptions(precision=3)
S

array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444])

##### 去掉所有的缺失值
要求：给定一维数组a包含缺失值，去掉他们

In [98]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

##### 设定数组的上下限
要求：给定数组a,将数组中大于30的数截断为30，小于10的数截断为10

In [100]:
np.set_printoptions(precision=2)
np.random.seed(1000)
a = np.random.uniform(1, 50, 20)
a

array([33.03,  6.64, 47.56, ..., 47.68, 46.63, 21.36])

In [106]:
np.clip(a, 10, 30)
a

array([33.03,  6.64, 47.56, ..., 47.68, 46.63, 21.36])